target 'AbbassiApp' do
  use_frameworks!
     pod 'Firebase/Analytics'
     pod 'Firebase/Auth'
     pod 'Firebase/Firestore'
     pod 'NVActivityIndicatorView'
     pod 'iOSDropDown'
     pod 'PMAlertController'
     pod 'Firebase/Crashlytics'

end

