//
//  phoneNumberViewController.swift
//  xmppTut
//
//  Created by Ahmed Sengab on 7/24/18.
//  Copyright © 2018 Ahmed Sengab. All rights reserved.
//

import UIKit

class phoneNumberViewController: mainClass {
    let lowerCaseString =  "abcdefghijklmnopqrstuvwxyz"
    let upperCaseString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    let specialCharacter = "!@#$%^&*"
    let codes = [
        "+93",
        "+355",
        "+213",
        "+1684",
        "+376",
        "+244",
        "+1264",
        "+1268",
        "+54",
        "+374",
        "+297",
        "+247",
        "+61",
        "+43",
        "+994",
        "+1242",
        "+973",
        "+880",
        "+1246",
        "+1268",
        "+375",
        "+32",
        "+501",
        "+229",
        "+1441",
        "+975",
        "+591",
        "+387",
        "+267",
        "+55",
        "+246",
        "+1284",
        "+673",
        "+359",
        "+226",
        "+257",
        "+855",
        "+237",
        "+1",
        "+238",
        "+345",
        "+236",
        "+235",
        "+56",
        "+86",
        "+61",
        "+61",
        "+57",
        "+269",
        "+242",
        "+243",
        "+682",
        "+506",
        "+385",
        "+53",
        "+599",
        "+537",
        "+420",
        "+45",
        "+246",
        "+253",
        "+1767",
        "+1809",
        "+1829",
        "+1849",
        "+670",
        "+56",
        "+593",
        "+20",
        "+503",
        "+240",
        "+291",
        "+372",
        "+251",
        "+500",
        "+298",
        "+679",
        "+358",
        "+33",
        "+596",
        "+594",
        "+689",
        "+241",
        "+220",
        "+995",
        "+49",
        "+233",
        "+350",
        "+30",
        "+299",
        "+1473",
        "+590",
        "+1671",
        "+502",
        "+245",
        "+224",
        "+595",
        "+509",
        "+504",
        "+852",
        "+36",
        "+354",
        "+91",
        "+62",
        "+98",
        "+964",
        "+353",
        "+972",
        "+39",
        "+225",
        "+1876",
        "+81",
        "+962",
        "+77",
        "+254",
        "+686",
        "+965",
        "+996",
        "+856",
        "+371",
        "+961",
        "+266",
        "+231",
        "+218",
        "+423",
        "+370",
        "+352",
        "+853",
        "+389",
        "+261",
        "+265",
        "+60",
        "+960",
        "+223",
        "+356",
        "+692",
        "+596",
        "+222",
        "+230",
        "+262",
        "+52",
        "+691",
        "+1808",
        "+373",
        "+377",
        "+976",
        "+382",
        "+1664",
        "+212",
        "+95",
        "+264",
        "+674",
        "+977",
        "+599",
        "+31",
        "+1869",
        "+687",
        "+64",
        "+505",
        "+227",
        "+234",
        "+683",
        "+672",
        "+850",
        "+1670",
        "+47",
        "+968",
        "+92",
        "+680",
        "+970",
        "+507",
        "+675",
        "+595",
        "+51",
        "+63",
        "+48",
        "+351",
        "+1787",
        "+1939",
        "+974",
        "+262",
        "+40",
        "+7",
        "+250",
        "+685",
        "+378",
        "+966",
        "+221",
        "+381",
        "+248",
        "+232",
        "+65",
        "+421",
        "+386",
        "+677",
        "+27",
        "+500",
        "+82",
        "+34",
        "+94",
        "+249",
        "+597",
        "+268",
        "+46",
        "+41",
        "+963",
        "+886",
        "+992",
        "+255",
        "+66",
        "+670",
        "+228",
        "+690",
        "+676",
        "+1868",
        "+216",
        "+90",
        "+993",
        "+1649",
        "+688",
        "+1340",
        "+256",
        "+380",
        "+971",
        "+44",
        "+1",
        "+598",
        "+998",
        "+678",
        "+58",
        "+84",
        "+1808",
        "+681",
        "+967",
        "+260",
        "+255",
        "+263"]
    let countryNames = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Ascension",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Barbuda",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "British Indian Ocean Territory",
        "British Virgin Islands",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos-Keeling Islands",
        "Colombia",
        "Comoros",
        "Congo - Brazzaville",
        "Congo - Kinshasa",
        "Cook Islands",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Curacao",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Diego Garcia",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Dominican Republic",
        "Dominican Republic",
        "East Timor",
        "Easter Island",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Antilles",
        "French Guiana",
        "French Polynesia",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea-Bissau",
        "Guinea",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Ivory Coast",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macau",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia",
        "Midway Island",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands Antilles",
        "Netherlands",
        "Nevis",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "North Korea",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestinian Territory",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russia",
        "Rwanda",
        "Samoa",
        "San Marino",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "South Korea",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "U.S. Virgin Islands",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Wake Island",
        "Wallis and Futuna",
        "Yemen",
        "Zambia",
        "Zanzibar",
        "Zimbabwe"]
    let mainLabel = UILabel()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        

        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    //// label in the screen ///////////
    ///// this is the mainLabel for all of the subclasses////
    func mainLabelView()
    {
        let navBarHeight = self.navigationController?.navigationBar.frame.height
        let screenSize = UIScreen.main.bounds
        let screenWidth = screenSize.width
        let screenHeight = screenSize.height
        print(screenWidth,screenHeight)
        self.mainLabel.textAlignment = .center
        self.view.addSubview(mainLabel);
        self.mainLabel.font = UIFont.systemFont(ofSize: 20)
        mainLabel.frame = CGRect(x: 0, y: navBarHeight!+0.08*screenHeight, width: screenWidth, height: 60)
    }
    func generateRandomPass()
    {
        var password = ""
        let token = UserDefaults.standard.string(forKey: "token")
        let upperCaseCount = upperCaseString.count
        let lowerCaseCount = lowerCaseString.count
        let specialCount = specialCharacter.count
        let tokenLength = token?.count
        for _ in 0...1
        {
            let loc = Int(arc4random_uniform(UInt32(upperCaseCount)))
            let charac = upperCaseString.index(upperCaseString.startIndex, offsetBy: loc)
            password.append(upperCaseString[charac])
            print(password)
        }
        for _ in 0...1
        {
            let loc = Int(arc4random_uniform(UInt32(lowerCaseCount)))
            let charac = lowerCaseString.index(lowerCaseString.startIndex, offsetBy: loc)
            password.append(lowerCaseString[charac])
            print(password)
        }
        for _ in 0...5
        {
            let loc = Int(arc4random_uniform(UInt32(tokenLength!)))
            let charac = token?.index((token?.startIndex)!, offsetBy: loc)
            password.append(token![charac!])
            print(password)
        }
        for _ in 0...2
        {
            let loc = Int(arc4random_uniform(UInt32(specialCount)))
            let charac = specialCharacter.index(specialCharacter.startIndex, offsetBy: loc)
            password.append(specialCharacter[charac])
            print(password)
        }
        UserDefaults.standard.set(password, forKey: "password")
        XMPPTest.shared.connect()
        self.performSegue(withIdentifier: "code", sender: self)
    }

}
